name: Deploy payment gateway backend service

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t srikar9/paymentgateway-app:latest .
      - name: Publish image to docker hub
        run: docker push srikar9/paymentgateway-app:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
       - name: Pull Docker image and restart containers
        run: |
          docker-compose pull
          docker-compose down
          docker-compose up -d